export function createRestaurantRuntimeCoreOptions(options = {}) {
  const {
    state,
    slug,
    allergenConfig,
    insertChangeLogEntry,
    fetchChangeLogEntries,
    getTipPinned,
    getMobileInfoPanel,
    setMobileInfoPanel,
    onZoomChange,
    normalizeAllergen,
    normalizeDietLabel,
    getDietAllergenConflicts,
    ALLERGENS,
    DIETS,
    ALLERGEN_EMOJI,
    DIET_EMOJI,
    supabaseClient,
    getSupabaseKey,
    getAiAssistEndpoint,
    current,
  } = options;

  return {
    state,
    slug,
    allergenConfig,
    insertChangeLogEntry,
    fetchChangeLogEntries,
    getTipPinned,
    getMobileInfoPanel,
    setMobileInfoPanel,
    onZoomChange,
    normalizeAllergen,
    normalizeDietLabel,
    getDietAllergenConflicts,
    ALLERGENS,
    DIETS,
    ALLERGEN_EMOJI,
    DIET_EMOJI,
    supabaseClient,
    getSupabaseKey,
    getAiAssistEndpoint,
    current,
  };
}
